<?PHP
 return [
	'RUR' => [
		'NumCode' => 810,
		'Nominal' => 1,
		'Name' => 'Рубли РФ',
		'Value' => 1,
	],
	'AUD' => [
		'NumCode' => 036,
		'Nominal' => 1,
		'Name' => 'Австралийский доллар',
		'Value' => 43.7534,
	],
	'AZN' => [
		'NumCode' => 944,
		'Nominal' => 1,
		'Name' => 'Азербайджанский манат',
		'Value' => 37.2102,
	],
	'GBP' => [
		'NumCode' => 826,
		'Nominal' => 1,
		'Name' => 'Фунт стерлингов',
		'Value' => 78.4859,
	],
	'AMD' => [
		'NumCode' => 051,
		'Nominal' => 100,
		'Name' => 'Армянских драмов',
		'Value' => 13.2592,
	],
	'BYN' => [
		'NumCode' => 933,
		'Nominal' => 1,
		'Name' => 'Белорусский рубль',
		'Value' => 31.1385,
	],
	'BGN' => [
		'NumCode' => 975,
		'Nominal' => 1,
		'Name' => 'Болгарский лев',
		'Value' => 35.9391,
	],
	'BRL' => [
		'NumCode' => 986,
		'Nominal' => 1,
		'Name' => 'Бразильский реал',
		'Value' => 16.7069,
	],
	'HUF' => [
		'NumCode' => 348,
		'Nominal' => 100,
		'Name' => 'Венгерских форинтов',
		'Value' => 21.5230,
	],
	'HKD' => [
		'NumCode' => 344,
		'Nominal' => 10,
		'Name' => 'Гонконгских долларов',
		'Value' => 80.7675,
	],
	'DKK' => [
		'NumCode' => 208,
		'Nominal' => 10,
		'Name' => 'Датских крон',
		'Value' => 94.1493,
	],
	'USD' => [
		'NumCode' => 840,
		'Nominal' => 1,
		'Name' => 'Доллар США',
		'Value' => 63.1271,
	],
	'EUR' => [
		'NumCode' => 978,
		'Nominal' => 1,
		'Name' => 'Евро',
		'Value' => 70.3110,
	],
	'INR' => [
		'NumCode' => 356,
		'Nominal' => 100,
		'Name' => 'Индийских рупий',
		'Value' => 91.4455,
	],
	'KZT' => [
		'NumCode' => 398,
		'Nominal' => 100,
		'Name' => 'Казахстанских тенге',
		'Value' => 16.3913,
	],
	'CAD' => [
		'NumCode' => 124,
		'Nominal' => 1,
		'Name' => 'Канадский доллар',
		'Value' => 47.8998,
	],
	'KGS' => [
		'NumCode' => 417,
		'Nominal' => 100,
		'Name' => 'Киргизских сомов',
		'Value' => 90.4659,
	],
	'CNY' => [
		'NumCode' => 156,
		'Nominal' => 10,
		'Name' => 'Китайских юаней',
		'Value' => 91.7545,
	],
	'MDL' => [
		'NumCode' => 498,
		'Nominal' => 10,
		'Name' => 'Молдавских леев',
		'Value' => 35.8168,
	],
	'NOK' => [
		'NumCode' => 578,
		'Nominal' => 10,
		'Name' => 'Норвежских крон',
		'Value' => 72.4891,
	],
	'PLN' => [
		'NumCode' => 985,
		'Nominal' => 1,
		'Name' => 'Польский злотый',
		'Value' => 16.4866,
	],
	'RON' => [
		'NumCode' => 946,
		'Nominal' => 1,
		'Name' => 'Румынский лей',
		'Value' => 14.8716,
	],
	'SGD' => [
		'NumCode' => 702,
		'Nominal' => 1,
		'Name' => 'Сингапурский доллар',
		'Value' => 46.1287,
	],
	'TJS' => [
		'NumCode' => 972,
		'Nominal' => 10,
		'Name' => 'Таджикских сомони',
		'Value' => 66.8599,
	],
	'TRY' => [
		'NumCode' => 949,
		'Nominal' => 1,
		'Name' => 'Турецкая лира',
		'Value' => 11.1069,
	],
	'TMT' => [
		'NumCode' => 934,
		'Nominal' => 1,
		'Name' => 'Новый туркменский манат',
		'Value' => 18.0621,
	],
	'UZS' => [
		'NumCode' => 860,
		'Nominal' => 10000,
		'Name' => 'Узбекских сумов',
		'Value' => 73.2163,
	],
	'UAH' => [
		'NumCode' => 980,
		'Nominal' => 10,
		'Name' => 'Украинских гривен',
		'Value' => 24.8190,
	],
	'CZK' => [
		'NumCode' => 203,
		'Nominal' => 10,
		'Name' => 'Чешских крон',
		'Value' => 27.5196,
	],
	'SEK' => [
		'NumCode' => 752,
		'Nominal' => 10,
		'Name' => 'Шведских крон',
		'Value' => 66.6291,
	],
	'CHF' => [
		'NumCode' => 756,
		'Nominal' => 1,
		'Name' => 'Швейцарский франк',
		'Value' => 63.6490,
	],
	'ZAR' => [
		'NumCode' => 710,
		'Nominal' => 10,
		'Name' => 'Южноафриканских рэндов',
		'Value' => 44.6033,
	],
	'KRW' => [
		'NumCode' => 410,
		'Nominal' => 1000,
		'Name' => 'Вон Республики Корея',
		'Value' => 53.3026,
	],
	'JPY' => [
		'NumCode' => 392,
		'Nominal' => 100,
		'Name' => 'Японских иен',
		'Value' => 58.0933,
	],
];
