<?php

    return [
//        'languages' => ['ru', 'en', 'ua'],
//        'languages_verbal' => ['ru' => 'Русский', 'en' => 'Английский', 'ua' => 'Украинский'],
        'languages' => ['ru'],
        'languages_verbal' => ['ru' => 'Русский'],
        'messages' => [
            'site',
            'auth',
            'buttons',
            'forms',
            'calendars',
            'admin_panel',
            'date_logger',
            'directory_person',
            'directory_firm',
            'customer',
            'customer_group',
            'orderer',
            'requester',
            'freetime',
            'treatment',
            'changehistory',
            'user',
            'role',
            'drug',
            'billing',
            'no_access',
            'menu',
            'dashboard',
            'alert',
            'promoter',
            'subdivision',
        ],
    ];