<?php

#########################################################################################
return [
    'BROWN' => [
        'level' => 1,
        'name' => 'BROWN',
        'price_from' => 0,
        'price_to' => 3499.99,
        'bonus' =>0,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#462712; color:#FFFFFF;">BROWN</span>',
        'color' => "#462712",
    ],
    'WHITE' => [
        'level' => 2,
        'name' => 'WHITE',
        'price_from' => 3500,
        'price_to' => 10499.99,
        'bonus' =>100000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#FFFFFF; color:#000000;">WHITE</span>',
        'color' => "#FFFFFF",
    ],
    'GREEN' => [
        'level' => 3,
        'name' => 'GREEN',
        'price_from' => 10500,
        'price_to' => 17499.99,
        'bonus' =>300000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#117E12; color:#FFFFFF;">GREEN</span>',
        'color' => "#117E12",
    ],
    'RED' => [
        'level' => 4,
        'name' => 'RED',
        'price_from' => 17500,
        'price_to' => 34999.99,
        'bonus' =>500000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#FD1C1B; color:#FFFFFF;">RED</span>',
        'color' => "#FD1C1B",
    ],
    'SILVER' => [
        'level' => 5,
        'name' => 'SILVER',
        'price_from' => 35000,
        'price_to' => 104999.99,
        'bonus' =>1000000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#B0B0B0; color:#000000;">SILVER</span>',
        'color' => "#B0B0B0",
    ],
    'BLACK' => [
        'level' => 6,
        'name' => 'BLACK',
        'price_from' => 105000,
        'price_to' => 174999.99,
        'bonus' =>3000000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#000000; color:#FFFFFF;">BLACK</span>',
        'color' => "#000000",
    ],
    'PLATINUM' => [
        'level' => 7,
        'name' => 'PLATINUM',
        'price_from' => 175000,
        'price_to' => 349999.99,
        'bonus' =>5000000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#E5E4E2; color:#000000;">PLATINUM</span>',
        'color' => "#E5E4E2",
    ],
    'IMPERIAL' => [
        'level' => 8,
        'name' => 'IMPERIAL',
        'price_from' => 350000,
        'price_to' => 999999999,
        'bonus' =>10000000,
        'logo' => '<span class="vista-box vista-box-sm" style="background-color:#A376D3; color:#FFFFFF;">IMPERIAL</span>',
        'color' => "#A376D3",
    ],
];
